const A={categories:[],links:[],user:null};const $=s=>document.querySelector(s);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.hidden=true,3500)}
function localMode(){return !window.supabaseReady}
function showLogin(){ $('#loginPanel').hidden=false;$('#adminPanel').hidden=true;$('#logout').hidden=true }
function showAdmin(){ $('#loginPanel').hidden=true;$('#adminPanel').hidden=false;$('#logout').hidden=false }
async function login(){if(localMode()){ $('#loginMsg').textContent='Configure primeiro o Supabase em js/supabase-config.js.';return}const email=$('#email').value.trim(),password=$('#password').value;const {data,error}=await portalSupabase.auth.signInWithPassword({email,password});if(error){$('#loginMsg').textContent=error.message;return}A.user=data.user;await loadAdmin()}
async function loadAdmin(){if(!A.user){const r=await portalSupabase.auth.getUser();A.user=r.data.user}if(!A.user){showLogin();return}const {data:profile,error:pe}=await portalSupabase.from('profiles').select('role').eq('id',A.user.id).single();if(pe||profile?.role!=='admin'){showLogin();$('#loginMsg').textContent='Usuário autenticado, mas sem permissão de administrador.';await portalSupabase.auth.signOut();return}showAdmin();$('#sessionInfo').textContent=`Administrador: ${A.user.email}`;await refresh();}
async function refresh(){const [c,l]=await Promise.all([portalSupabase.from('categories').select('*').order('sort_order'),portalSupabase.from('links').select('*, categories(name)').order('sort_order')]);if(c.error||l.error){toast(c.error?.message||l.error?.message);return}A.categories=c.data||[];A.links=(l.data||[]).map(x=>({...x,category_name:x.categories?.name||'Sem categoria'}));renderCategories();renderLinks()}
function renderCategories(){$('#categoryAdmin').innerHTML=A.categories.map(c=>`<div class="admin-cat"><span>${esc(c.icon||'📁')}</span><div><b>${esc(c.name)}</b><small>${A.links.filter(x=>x.category_id===c.id).length} atalhos</small></div></div>`).join('')}
function renderLinks(){const q=$('#adminSearch').value.toLocaleLowerCase('pt-BR');const rows=A.links.filter(x=>(x.name+' '+x.category_name+' '+x.description).toLocaleLowerCase('pt-BR').includes(q));$('#adminCount').textContent=`${rows.length} atalhos`;$('#adminList').innerHTML=rows.map(x=>`<div class="admin-row"><div class="admin-row-main"><span>${esc(x.category_name)}</span><b>${esc(x.name)}</b><small>${esc(x.url)}</small></div><div class="admin-row-actions"><button data-edit="${x.id}" class="secondary">Editar</button><button data-delete="${x.id}" class="danger">Excluir</button></div></div>`).join('')||'<div class="empty">Nenhum atalho encontrado.</div>'}
function openEditor(x=null){$('#editor').hidden=false;$('#editId').value=x?.id||'';$('#editorEyebrow').textContent=x?'EDITAR ATALHO':'NOVO ATALHO';$('#editorTitle').textContent=x?'Editar atalho':'Cadastrar atalho';$('#linkName').value=x?.name||'';$('#linkDescription').value=x?.description||'';$('#linkUrl').value=x?.url||'';$('#linkType').value=x?.link_type||'internal';$('#linkActive').checked=x?.active!==false;$('#linkCategory').innerHTML=A.categories.map(c=>`<option value="${c.id}" ${x?.category_id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}
function closeEditor(){$('#editor').hidden=true;$('#linkForm').reset()}
async function saveLink(e){e.preventDefault();const id=$('#editId').value;const payload={name:$('#linkName').value.trim(),category_id:$('#linkCategory').value,description:$('#linkDescription').value.trim(),url:$('#linkUrl').value.trim(),link_type:$('#linkType').value,active:$('#linkActive').checked};let r;if(id)r=await portalSupabase.from('links').update({...payload,updated_at:new Date().toISOString()}).eq('id',id);else{payload.sort_order=A.links.length+1;r=await portalSupabase.from('links').insert(payload)}if(r.error){$('#formMsg').textContent=r.error.message;return}closeEditor();await refresh();toast('Atalho salvo.');}
async function deleteLink(id){const x=A.links.find(v=>v.id===id);if(!x||!confirm(`Excluir o atalho “${x.name}”?`))return;const {error}=await portalSupabase.from('links').delete().eq('id',id);if(error)toast(error.message);else{await refresh();toast('Atalho excluído.')}}
async function saveCategory(e){e.preventDefault();const payload={name:$('#categoryName').value.trim(),description:$('#categoryDescription').value.trim(),icon:$('#categoryIcon').value.trim()||'📁',sort_order:A.categories.length+1};const {error}=await portalSupabase.from('categories').insert(payload);if(error){$('#categoryMsg').textContent=error.message;return}$('#categoryModal').hidden=true;e.target.reset();await refresh();toast('Categoria criada.')}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();login()});$('#logout').onclick=async()=>{await portalSupabase.auth.signOut();A.user=null;showLogin()};$('#newLink').onclick=()=>openEditor();$('#closeEditor').onclick=closeEditor;$('#cancelEditor').onclick=closeEditor;$('#linkForm').addEventListener('submit',saveLink);$('#newCategory').onclick=()=>$('#categoryModal').hidden=false;$('#closeCategory').onclick=$('#cancelCategory').onclick=()=>$('#categoryModal').hidden=true;$('#categoryForm').addEventListener('submit',saveCategory);$('#adminSearch').addEventListener('input',renderLinks);document.addEventListener('click',e=>{const ed=e.target.closest('[data-edit]');if(ed){openEditor(A.links.find(x=>x.id===ed.dataset.edit));return}const del=e.target.closest('[data-delete]');if(del)deleteLink(del.dataset.delete)});$('#theme').onclick=()=>{const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'light':'dark';localStorage.setItem('pti_theme',d?'light':'dark')};const t=localStorage.getItem('pti_theme');if(t)document.documentElement.dataset.theme=t;
(async()=>{if(localMode()){showLogin();$('#loginMsg').textContent='Configure o Supabase para ativar a administração.';return}const r=await portalSupabase.auth.getUser();A.user=r.data.user;if(A.user)await loadAdmin();else showLogin()})();
