const S={cat:'',q:'',mode:'all',data:window.portalData,recent:JSON.parse(localStorage.getItem('pti_recent')||'[]'),favorites:JSON.parse(localStorage.getItem('pti_fav')||'[]'),dbFavorites:new Set(),usingDb:false};
const $=s=>document.querySelector(s);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const icon=c=>({'Manuais':'📘','Telefonia':'☎️','Rede':'🌐','Softwares':'💻','Administrativo':'📋','Termos':'📄','Reconhecimento de curso':'🎓','Planejamento':'📅','SENHAS':'🔑','Datashow':'📽️','Contratos OBC':'📦'}[c]||'📁');
function saveLocal(){localStorage.setItem('pti_recent',JSON.stringify(S.recent));localStorage.setItem('pti_fav',JSON.stringify(S.favorites));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.hidden=true,3500)}
function getId(x){return x.id}
function isFav(x){return S.usingDb?S.dbFavorites.has(x.id):S.favorites.includes(x.id)}
function resolveUrl(x){let u=(x.url||'').trim();if(/^https?:\/\//i.test(u))return u;const cfg=window.PORTAL_CONFIG||{};const maps=cfg.networkShareMappings||{};
  for(const [from,to] of Object.entries(maps)){if(u.toLowerCase().includes(from.toLowerCase())){let rest=u.slice(u.toLowerCase().indexOf(from.toLowerCase())+from.length).replace(/^[/\\]+/,'').replaceAll('\\','/');return to.replace(/\/$/,'')+'/'+rest;}}
  if(cfg.internalFilesBaseUrl){let clean=u.replace(/^file:\/\//i,'').replace(/^[/\\]+/,'').replaceAll('\\','/').replace(/^\.\.\//,'');return cfg.internalFilesBaseUrl.replace(/\/$/,'')+'/'+clean;}
  return null;
}
function openItem(x){const url=resolveUrl(x);if(!url){toast('Este atalho ainda precisa de uma URL HTTP/HTTPS interna. Acesse Administração para configurá-lo.');return}
  S.recent=[x.id,...S.recent.filter(v=>v!==x.id)].slice(0,8);saveLocal();renderQuick();window.open(url,'_blank','noopener');}
function filtered(){let a=[...S.data.links];if(S.cat)a=a.filter(x=>x.category===S.cat);if(S.mode==='fav')a=a.filter(isFav);if(S.mode==='recent')a=a.filter(x=>S.recent.includes(x.id)).sort((x,y)=>S.recent.indexOf(x.id)-S.recent.indexOf(y.id));if(S.q){const q=S.q.toLocaleLowerCase('pt-BR');const terms=q.split(/\s+/).filter(Boolean);a=a.filter(x=>terms.every(term=>(x.name+' '+x.category+' '+x.description+' '+x.url).toLocaleLowerCase('pt-BR').includes(term)))}return a}
function card(x){const f=isFav(x);const type=/^https?:\/\//i.test(x.url)?'WEB':(resolveUrl(x)?'REDE / HTTPS':'REDE / CONFIGURAR');return `<article class="card"><div class="ct"><span class="ico">${icon(x.category)}</span><button class="star ${f?'on':''}" data-f="${esc(x.id)}" title="${f?'Remover favorito':'Adicionar favorito'}">${f?'★':'☆'}</button></div><h3>${esc(x.name)}</h3><p>${esc(x.description||x.category)}</p><div class="cf"><small>${type}</small><button data-o="${esc(x.id)}">Abrir ↗</button></div></article>`}
function renderQuick(){const ids=[...S.favorites,...S.recent.filter(x=>!S.favorites.includes(x))].slice(0,8);const a=ids.map(id=>S.data.links.find(x=>String(x.id)===String(id))).filter(Boolean);$('#quickGrid').innerHTML=a.length?a.map(card).join(''):'<div class="quick-empty">Favorite atalhos ou abra documentos para vê-los aqui.</div>';}
function render(){const a=filtered();$('#grid').innerHTML=a.map(card).join('');$('#empty').hidden=a.length>0;$('#count').textContent=`${a.length} ${a.length===1?'atalho':'atalhos'}`;$('#sectionTitle').textContent=S.mode==='fav'?'Favoritos':S.mode==='recent'?'Recentes':S.cat||'Todos os atalhos';$('#chips').innerHTML=S.data.categories.map(c=>`<button class="chip ${S.cat===c?'sel':''}" data-c="${esc(c)}">${icon(c)} ${esc(c)}</button>`).join('');renderQuick();}
async function toggleFavorite(x){if(!S.usingDb){S.favorites=S.favorites.includes(x.id)?S.favorites.filter(v=>v!==x.id):[...S.favorites,x.id];saveLocal();render();return}
  const user=(await portalSupabase.auth.getUser()).data.user;if(!user){toast('Entre na administração para sincronizar favoritos.');return}
  if(S.dbFavorites.has(x.id)){const {error}=await portalSupabase.from('favorites').delete().eq('user_id',user.id).eq('link_id',x.id);if(error)toast(error.message);else S.dbFavorites.delete(x.id)}
  else {const {error}=await portalSupabase.from('favorites').insert({user_id:user.id,link_id:x.id});if(error)toast(error.message);else S.dbFavorites.add(x.id)}render();}
async function loadDb(){if(!window.supabaseReady)return;const [{data:cats,error:e1},{data:links,error:e2}]=await Promise.all([portalSupabase.from('categories').select('*').eq('active',true).order('sort_order'),portalSupabase.from('links').select('*, categories(name)').eq('active',true).order('sort_order')]);if(e1||e2){toast('Supabase configurado, mas não foi possível carregar os dados. Verifique as políticas RLS.');return}
  S.data={categories:cats.map(c=>c.name),links:links.map(l=>({...l,category:l.categories?.name||'Sem categoria'}))};S.usingDb=true;const {data:{user}}=await portalSupabase.auth.getUser();if(user){const {data:f}=await portalSupabase.from('favorites').select('link_id').eq('user_id',user.id);S.dbFavorites=new Set((f||[]).map(v=>v.link_id));}}
document.addEventListener('click',e=>{const f=e.target.closest('[data-f]');if(f){const x=S.data.links.find(v=>String(v.id)===f.dataset.f);if(x)toggleFavorite(x);return}const o=e.target.closest('[data-o]');if(o){const x=S.data.links.find(v=>String(v.id)===o.dataset.o);if(x)openItem(x);return}const c=e.target.closest('[data-c]');if(c){S.cat=S.cat===c.dataset.c?'':c.dataset.c;S.mode='all';render()}});
$('#q').addEventListener('input',e=>{S.q=e.target.value;S.cat='';S.mode='all';render()});$('#clear').onclick=()=>{$('#q').value='';S.q='';render()};$('#favoritesBtn').onclick=()=>{S.mode='fav';S.cat='';render()};$('#recentBtn').onclick=()=>{S.mode='recent';S.cat='';render()};$('#allBtn').onclick=()=>{S.mode='all';S.cat='';$('#q').value='';S.q='';render()};$('#theme').onclick=()=>{const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'light':'dark';localStorage.setItem('pti_theme',d?'light':'dark')};
(async()=>{const t=localStorage.getItem('pti_theme');if(t)document.documentElement.dataset.theme=t;await loadDb();$('#footerInfo').textContent=`${S.data.links.length} atalhos · ${S.data.categories.length} categorias${S.usingDb?' · Supabase conectado':' · modo local'}`;render();})();
