-- MIGRAÇÃO DOS LINKS DA PLANILHA Controle Geral.xlsx
-- Execute este arquivo DEPOIS do supabase-schema.sql já executado.
-- Ele corrige as categorias e grava os 30 hyperlinks originais.
-- Não apaga seus registros; atualiza os existentes pelo nome e insere os ausentes.
--
-- CORREÇÃO: a coluna link_type usada abaixo não existe no schema original
-- (supabase-schema.sql só cria id/category_id/name/url/description/sort_order/
-- active/created_at/updated_at). Sem esta linha, todo o script falha com
-- "column link_type does not exist".
alter table public.links add column if not exists link_type text default 'internal';

with c as (select id from public.categories where name = 'Telefonia') update public.links l set category_id=c.id, description='Levantamento das centrais telefônicas e ramais VoIP.', url='file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Manuais\Central%20Telefonica\Levantamento%20Centrais%20Telefonicas.xlsx', sort_order=1, active=true, link_type='internal', updated_at=now() from c where l.name='Levantamento Centrais Telefonicas - Ramais VoIP';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Levantamento Centrais Telefonicas - Ramais VoIP','Levantamento das centrais telefônicas e ramais VoIP.','file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Manuais\Central%20Telefonica\Levantamento%20Centrais%20Telefonicas.xlsx','internal',1,true from public.categories c where c.name='Telefonia' and not exists (select 1 from public.links l where l.name='Levantamento Centrais Telefonicas - Ramais VoIP');
with c as (select id from public.categories where name = 'Telefonia') update public.links l set category_id=c.id, description='Controle de linhas Vivo e aparelhos celulares.', url='file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Manuais\Central%20Telefonica\Controle%20linhas%20da%20VIVO%20+%20Aparelhos.xlsx', sort_order=2, active=true, link_type='internal', updated_at=now() from c where l.name='Controle de Linhas ViVo e Aparelhos Celulares';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Controle de Linhas ViVo e Aparelhos Celulares','Controle de linhas Vivo e aparelhos celulares.','file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Manuais\Central%20Telefonica\Controle%20linhas%20da%20VIVO%20+%20Aparelhos.xlsx','internal',2,true from public.categories c where c.name='Telefonia' and not exists (select 1 from public.links l where l.name='Controle de Linhas ViVo e Aparelhos Celulares');
with c as (select id from public.categories where name = 'Rede') update public.links l set category_id=c.id, description='Diagrama de switches gerenciáveis e portas.', url='file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Redes\Diagramas\Diagrama_%20Rede_Xanxere_infra_SW_Gerenciaveis_Portas.vsdx', sort_order=3, active=true, link_type='internal', updated_at=now() from c where l.name='Diagrama - Switchs Gerenciaveis + Portas';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Diagrama - Switchs Gerenciaveis + Portas','Diagrama de switches gerenciáveis e portas.','file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Redes\Diagramas\Diagrama_%20Rede_Xanxere_infra_SW_Gerenciaveis_Portas.vsdx','internal',3,true from public.categories c where c.name='Rede' and not exists (select 1 from public.links l where l.name='Diagrama - Switchs Gerenciaveis + Portas');
with c as (select id from public.categories where name = 'Rede') update public.links l set category_id=c.id, description='Comandos utilizados para configuração dos switches Extreme.', url='file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Redes\Conf%20Switchs%20Gerenciaveis\Comandos%20Extreme.docx', sort_order=4, active=true, link_type='internal', updated_at=now() from c where l.name='Comandos - Configurar Switch Extreme';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Comandos - Configurar Switch Extreme','Comandos utilizados para configuração dos switches Extreme.','file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Redes\Conf%20Switchs%20Gerenciaveis\Comandos%20Extreme.docx','internal',4,true from public.categories c where c.name='Rede' and not exists (select 1 from public.links l where l.name='Comandos - Configurar Switch Extreme');
with c as (select id from public.categories where name = 'Rede') update public.links l set category_id=c.id, description='Diagrama geral da rede de Xanxerê.', url='file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Redes\Diagramas\Diagrama_Rede_UNOESC_Xanxerê_Geral.vsdx', sort_order=5, active=true, link_type='internal', updated_at=now() from c where l.name='Diagrama - Rede Xanxerê Geral';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Diagrama - Rede Xanxerê Geral','Diagrama geral da rede de Xanxerê.','file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Redes\Diagramas\Diagrama_Rede_UNOESC_Xanxerê_Geral.vsdx','internal',5,true from public.categories c where c.name='Rede' and not exists (select 1 from public.links l where l.name='Diagrama - Rede Xanxerê Geral');
with c as (select id from public.categories where name = 'Rede') update public.links l set category_id=c.id, description='Procedimento para reiniciar uma porta PoE do Switch Extreme 220.', url='file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Redes\Reiniciando%20apenas%201%20porta%20do%20Switch%20PoE%20Extreme%20220.docx', sort_order=6, active=true, link_type='internal', updated_at=now() from c where l.name='Reiniciar porta POE - Switch Extreme 220';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Reiniciar porta POE - Switch Extreme 220','Procedimento para reiniciar uma porta PoE do Switch Extreme 220.','file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Redes\Reiniciando%20apenas%201%20porta%20do%20Switch%20PoE%20Extreme%20220.docx','internal',6,true from public.categories c where c.name='Rede' and not exists (select 1 from public.links l where l.name='Reiniciar porta POE - Switch Extreme 220');
with c as (select id from public.categories where name = 'Administrativo') update public.links l set category_id=c.id, description='Levantamento de equipamentos do campus Xanxerê.', url='Levantamento%20equipamento%20XXE.xlsx', sort_order=7, active=true, link_type='internal', updated_at=now() from c where l.name='Levantamento Equipamentos Xanxerê';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Levantamento Equipamentos Xanxerê','Levantamento de equipamentos do campus Xanxerê.','Levantamento%20equipamento%20XXE.xlsx','internal',7,true from public.categories c where c.name='Administrativo' and not exists (select 1 from public.links l where l.name='Levantamento Equipamentos Xanxerê');
with c as (select id from public.categories where name = 'Administrativo') update public.links l set category_id=c.id, description='Levantamento de equipamentos de Xaxim.', url='Levantamento%20equipamento%20XXM.xlsx', sort_order=8, active=true, link_type='internal', updated_at=now() from c where l.name='Levantamento Equipamentos Xaxim';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Levantamento Equipamentos Xaxim','Levantamento de equipamentos de Xaxim.','Levantamento%20equipamento%20XXM.xlsx','internal',8,true from public.categories c where c.name='Administrativo' and not exists (select 1 from public.links l where l.name='Levantamento Equipamentos Xaxim');
with c as (select id from public.categories where name = 'Administrativo') update public.links l set category_id=c.id, description='Levantamento de nobreaks.', url='NoBreak%20-%20Levantamento.xlsx', sort_order=9, active=true, link_type='internal', updated_at=now() from c where l.name='Levantamento Nobreks';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Levantamento Nobreks','Levantamento de nobreaks.','NoBreak%20-%20Levantamento.xlsx','internal',9,true from public.categories c where c.name='Administrativo' and not exists (select 1 from public.links l where l.name='Levantamento Nobreks');
with c as (select id from public.categories where name = 'Termos') update public.links l set category_id=c.id, description='Termo de responsabilidade para utilização da rede IoT.', url='Termo%20de%20Responsabilidade%20rede%20IoT%20-%20JBA.docx', sort_order=10, active=true, link_type='internal', updated_at=now() from c where l.name='Termo Responsabilidade rede IoT';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Termo Responsabilidade rede IoT','Termo de responsabilidade para utilização da rede IoT.','Termo%20de%20Responsabilidade%20rede%20IoT%20-%20JBA.docx','internal',10,true from public.categories c where c.name='Termos' and not exists (select 1 from public.links l where l.name='Termo Responsabilidade rede IoT');
with c as (select id from public.categories where name = 'Termos') update public.links l set category_id=c.id, description='Termo/política de uso e empréstimo de equipamentos.', url='Portaria_nº15_LGPD_-_Política_de_Uso_dos_Equipamentos_de_Informática_e_Rede.pdf', sort_order=11, active=true, link_type='internal', updated_at=now() from c where l.name='Termo Emprestimo de Equipamentos';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Termo Emprestimo de Equipamentos','Termo/política de uso e empréstimo de equipamentos.','Portaria_nº15_LGPD_-_Política_de_Uso_dos_Equipamentos_de_Informática_e_Rede.pdf','internal',11,true from public.categories c where c.name='Termos' and not exists (select 1 from public.links l where l.name='Termo Emprestimo de Equipamentos');
with c as (select id from public.categories where name = 'Softwares') update public.links l set category_id=c.id, description='Caminho de instalação, senhas e quantidade de computadores com Kaspersky.', url='Kaspersky%20-%20Caminho%20de%20Instalação,%20senhas%20e%20qtd%20micros%20instalados.xlsx', sort_order=12, active=true, link_type='internal', updated_at=now() from c where l.name='Kaspersky';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Kaspersky','Caminho de instalação, senhas e quantidade de computadores com Kaspersky.','Kaspersky%20-%20Caminho%20de%20Instalação,%20senhas%20e%20qtd%20micros%20instalados.xlsx','internal',12,true from public.categories c where c.name='Softwares' and not exists (select 1 from public.links l where l.name='Kaspersky');
with c as (select id from public.categories where name = 'Administrativo') update public.links l set category_id=c.id, description='Informações de acesso aos servidores e sistemas.', url='Acesso%20aos%20SERVIDORES%20e%20SISTEMAS.xlsx', sort_order=13, active=true, link_type='internal', updated_at=now() from c where l.name='Acesso aos Servidores e Sistemas';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Acesso aos Servidores e Sistemas','Informações de acesso aos servidores e sistemas.','Acesso%20aos%20SERVIDORES%20e%20SISTEMAS.xlsx','internal',13,true from public.categories c where c.name='Administrativo' and not exists (select 1 from public.links l where l.name='Acesso aos Servidores e Sistemas');
with c as (select id from public.categories where name = 'Reconhecimento de curso') update public.links l set category_id=c.id, description='Pasta de arquivos para processos de reconhecimento de curso.', url='../Reconhecimento%20Curso', sort_order=14, active=true, link_type='internal', updated_at=now() from c where l.name='Arquivos para Reconhecimento de Curso';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Arquivos para Reconhecimento de Curso','Pasta de arquivos para processos de reconhecimento de curso.','../Reconhecimento%20Curso','internal',14,true from public.categories c where c.name='Reconhecimento de curso' and not exists (select 1 from public.links l where l.name='Arquivos para Reconhecimento de Curso');
with c as (select id from public.categories where name = 'Softwares') update public.links l set category_id=c.id, description='Levantamento de softwares por laboratório e setor.', url='../Softwares%20e%20Licenças/Levantamento%20Softwares%20por%20Laboratorio-Setores.xlsx', sort_order=15, active=true, link_type='internal', updated_at=now() from c where l.name='Softwares por Laboratórios e Setores';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Softwares por Laboratórios e Setores','Levantamento de softwares por laboratório e setor.','../Softwares%20e%20Licenças/Levantamento%20Softwares%20por%20Laboratorio-Setores.xlsx','internal',15,true from public.categories c where c.name='Softwares' and not exists (select 1 from public.links l where l.name='Softwares por Laboratórios e Setores');
with c as (select id from public.categories where name = 'Softwares') update public.links l set category_id=c.id, description='Controle de contratos de software.', url='../Softwares%20e%20Licenças/Controle%20De%20Softwares/Controle%20CONTRATOS_SOFTWARE%20Xanxerê.xlsx', sort_order=16, active=true, link_type='internal', updated_at=now() from c where l.name='Controle Contratos Software';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Controle Contratos Software','Controle de contratos de software.','../Softwares%20e%20Licenças/Controle%20De%20Softwares/Controle%20CONTRATOS_SOFTWARE%20Xanxerê.xlsx','internal',16,true from public.categories c where c.name='Softwares' and not exists (select 1 from public.links l where l.name='Controle Contratos Software');
with c as (select id from public.categories where name = 'Administrativo') update public.links l set category_id=c.id, description='Quantidade de computadores e impressoras de Xanxerê e Xaxim.', url='Atualização%20Micros%20e%20Impressoras%20Xanxerê%20e%20Xaxim.xlsx', sort_order=17, active=true, link_type='internal', updated_at=now() from c where l.name='Quantidade de Comoputadores e Impressoras';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Quantidade de Comoputadores e Impressoras','Quantidade de computadores e impressoras de Xanxerê e Xaxim.','Atualização%20Micros%20e%20Impressoras%20Xanxerê%20e%20Xaxim.xlsx','internal',17,true from public.categories c where c.name='Administrativo' and not exists (select 1 from public.links l where l.name='Quantidade de Comoputadores e Impressoras');
with c as (select id from public.categories where name = 'Administrativo') update public.links l set category_id=c.id, description='Checklist de instalação, programas e configurações de computadores administrativos.', url='Checklist%20instalação%20micros%20ADM.docx', sort_order=18, active=true, link_type='internal', updated_at=now() from c where l.name='Checklist PC Adm - Programas e Configurações';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Checklist PC Adm - Programas e Configurações','Checklist de instalação, programas e configurações de computadores administrativos.','Checklist%20instalação%20micros%20ADM.docx','internal',18,true from public.categories c where c.name='Administrativo' and not exists (select 1 from public.links l where l.name='Checklist PC Adm - Programas e Configurações');
with c as (select id from public.categories where name = 'Planejamento') update public.links l set category_id=c.id, description='Planejamento de TI para 2027.', url='../Planejamento/Planejamento%202027.xlsx', sort_order=19, active=true, link_type='internal', updated_at=now() from c where l.name='Planejamento 2027';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Planejamento 2027','Planejamento de TI para 2027.','../Planejamento/Planejamento%202027.xlsx','internal',19,true from public.categories c where c.name='Planejamento' and not exists (select 1 from public.links l where l.name='Planejamento 2027');
with c as (select id from public.categories where name = 'Planejamento') update public.links l set category_id=c.id, description='Planejamento de TI para 2026.', url='../Planejamento/Planejamento%202026.xlsx', sort_order=20, active=true, link_type='internal', updated_at=now() from c where l.name='Planejamento 2026';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Planejamento 2026','Planejamento de TI para 2026.','../Planejamento/Planejamento%202026.xlsx','internal',20,true from public.categories c where c.name='Planejamento' and not exists (select 1 from public.links l where l.name='Planejamento 2026');
with c as (select id from public.categories where name = 'Manuais') update public.links l set category_id=c.id, description='Procedimento para desligamento dos servidores.', url='../Manuais/Manual%20para%20desligar%20SERVIDORES.docx', sort_order=21, active=true, link_type='internal', updated_at=now() from c where l.name='Manual para Desligar os SERVIDORES';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Manual para Desligar os SERVIDORES','Procedimento para desligamento dos servidores.','../Manuais/Manual%20para%20desligar%20SERVIDORES.docx','internal',21,true from public.categories c where c.name='Manuais' and not exists (select 1 from public.links l where l.name='Manual para Desligar os SERVIDORES');
with c as (select id from public.categories where name = 'Manuais') update public.links l set category_id=c.id, description='Manual para ligar o sistema de som do anfiteatro.', url='../Manuais/MANUAL%20PARA%20LIGAR%20O%20SISTEMA%20DE%20SOM%20DO%20ANFITEATRO.pdf', sort_order=22, active=true, link_type='internal', updated_at=now() from c where l.name='Manual para Ligar a Mesa de Som ANFITEATRO';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Manual para Ligar a Mesa de Som ANFITEATRO','Manual para ligar o sistema de som do anfiteatro.','../Manuais/MANUAL%20PARA%20LIGAR%20O%20SISTEMA%20DE%20SOM%20DO%20ANFITEATRO.pdf','internal',22,true from public.categories c where c.name='Manuais' and not exists (select 1 from public.links l where l.name='Manual para Ligar a Mesa de Som ANFITEATRO');
with c as (select id from public.categories where name = 'Manuais') update public.links l set category_id=c.id, description='Manual do PH Software utilizado no laboratório de contábeis.', url='../Manuais/PH%20Softwares.docx', sort_order=23, active=true, link_type='internal', updated_at=now() from c where l.name='Manual PH Software - Lab Contabeis';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Manual PH Software - Lab Contabeis','Manual do PH Software utilizado no laboratório de contábeis.','../Manuais/PH%20Softwares.docx','internal',23,true from public.categories c where c.name='Manuais' and not exists (select 1 from public.links l where l.name='Manual PH Software - Lab Contabeis');
with c as (select id from public.categories where name = 'Manuais') update public.links l set category_id=c.id, description='Orientação para limpeza de cache dos navegadores.', url='../Manuais/Como%20limpar%20o%20cache%20do%20seu%20navegador.pdf', sort_order=24, active=true, link_type='internal', updated_at=now() from c where l.name='Limpar Cache Navegadores';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Limpar Cache Navegadores','Orientação para limpeza de cache dos navegadores.','../Manuais/Como%20limpar%20o%20cache%20do%20seu%20navegador.pdf','internal',24,true from public.categories c where c.name='Manuais' and not exists (select 1 from public.links l where l.name='Limpar Cache Navegadores');
with c as (select id from public.categories where name = 'Administrativo') update public.links l set category_id=c.id, description='Fluxograma do processo de demandas.', url='Fluxograma%20Demandas.vsdx', sort_order=25, active=true, link_type='internal', updated_at=now() from c where l.name='Fluxograma das Demandas';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Fluxograma das Demandas','Fluxograma do processo de demandas.','Fluxograma%20Demandas.vsdx','internal',25,true from public.categories c where c.name='Administrativo' and not exists (select 1 from public.links l where l.name='Fluxograma das Demandas');
with c as (select id from public.categories where name = 'SENHAS') update public.links l set category_id=c.id, description='Documento com informações de acesso aos DVRs.', url='Senhas%20DVR%20Expressivo%20XXE%20e%20UNOESC%20XXM.docx', sort_order=26, active=true, link_type='internal', updated_at=now() from c where l.name='Senhas DVRs';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Senhas DVRs','Documento com informações de acesso aos DVRs.','Senhas%20DVR%20Expressivo%20XXE%20e%20UNOESC%20XXM.docx','internal',26,true from public.categories c where c.name='SENHAS' and not exists (select 1 from public.links l where l.name='Senhas DVRs');
with c as (select id from public.categories where name = 'Datashow') update public.links l set category_id=c.id, description='Levantamento dos equipamentos Datashow.', url='Levantamento%20Datashow.xlsx', sort_order=27, active=true, link_type='internal', updated_at=now() from c where l.name='Levantamento Datashow';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Levantamento Datashow','Levantamento dos equipamentos Datashow.','Levantamento%20Datashow.xlsx','internal',27,true from public.categories c where c.name='Datashow' and not exists (select 1 from public.links l where l.name='Levantamento Datashow');
with c as (select id from public.categories where name = 'SENHAS') update public.links l set category_id=c.id, description='Arquivo de referência para senhas.', url='file:///K:\TI\Manual.txt', sort_order=28, active=true, link_type='internal', updated_at=now() from c where l.name='Senhas';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Senhas','Arquivo de referência para senhas.','file:///K:\TI\Manual.txt','internal',28,true from public.categories c where c.name='SENHAS' and not exists (select 1 from public.links l where l.name='Senhas');
with c as (select id from public.categories where name = 'Termos') update public.links l set category_id=c.id, description='Ficha/termo para acesso à rede e uso dos computadores.', url='Termo_de_Responsabilidade_Computadores.doc', sort_order=29, active=true, link_type='internal', updated_at=now() from c where l.name='Ficha de acesso a rede e uso dos computadores';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Ficha de acesso a rede e uso dos computadores','Ficha/termo para acesso à rede e uso dos computadores.','Termo_de_Responsabilidade_Computadores.doc','internal',29,true from public.categories c where c.name='Termos' and not exists (select 1 from public.links l where l.name='Ficha de acesso a rede e uso dos computadores');
with c as (select id from public.categories where name = 'Contratos OBC') update public.links l set category_id=c.id, description='Pasta com orientações e documentação de contratos OBC.', url='file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Contratos\OBC', sort_order=30, active=true, link_type='internal', updated_at=now() from c where l.name='Orientações Contratos OBC';
insert into public.links (category_id,name,description,url,link_type,sort_order,active) select c.id,'Orientações Contratos OBC','Pasta com orientações e documentação de contratos OBC.','file:///\\arquivos\ti\G_Xanxere_TI\Documentação\Contratos\OBC','internal',30,true from public.categories c where c.name='Contratos OBC' and not exists (select 1 from public.links l where l.name='Orientações Contratos OBC');

select l.name, c.name as category, l.url, l.sort_order from public.links l left join public.categories c on c.id=l.category_id order by l.sort_order;